[pytest]
addopts = -v -s --disable-warnings
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO
markers =
    android: Android Appium tests
    web: Web Playwright tests
